ERROR 2025-08-28 18:01:43,889 log 18112 2672 Internal Server Error: /admin/notifications/notificationpreference/
Traceback (most recent call last):
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: notifications_notificationpreference

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 234, in execute
    return self._record(super().execute, sql, params)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: notifications_notificationpreference
ERROR 2025-08-28 18:01:59,428 log 18112 2672 Internal Server Error: /admin/notifications/notification/
Traceback (most recent call last):
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: notifications_notification

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 234, in execute
    return self._record(super().execute, sql, params)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: notifications_notification
ERROR 2025-08-28 18:02:04,285 log 18112 2672 Internal Server Error: /admin/notifications/notificationlog/
Traceback (most recent call last):
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: notifications_notificationlog

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 234, in execute
    return self._record(super().execute, sql, params)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: notifications_notificationlog
ERROR 2025-08-28 18:02:10,622 log 18112 2672 Internal Server Error: /admin/notifications/notification/
Traceback (most recent call last):
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: notifications_notification

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 234, in execute
    return self._record(super().execute, sql, params)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: notifications_notification
ERROR 2025-08-28 18:04:14,645 log 18112 2672 Internal Server Error: /admin/notifications/notificationlog/
Traceback (most recent call last):
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: notifications_notificationlog

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 234, in execute
    return self._record(super().execute, sql, params)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: notifications_notificationlog
ERROR 2025-08-28 18:04:31,143 log 18112 2672 Internal Server Error: /admin/notifications/notificationlog/
Traceback (most recent call last):
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: notifications_notificationlog

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
        request,
    ...<12 lines>...
        self.search_help_text,
    )
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\views\main.py", line 146, in __init__
    self.get_results(request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\contrib\admin\views\main.py", line 313, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\core\paginator.py", line 110, in count
    return c()
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\sql\query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 234, in execute
    return self._record(super().execute, sql, params)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\ModernTech\.virtualenvs\Hospital_Queue_Management_API-LziE1Wer\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: notifications_notificationlog
